server:
  port: 8081
  address: 127.0.0.1
  tomcat:
    uri-encoding: UTF-8

mybatis:
  config-location: classpath:config/mybatis-config.xml
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.lyp.count

spring:
  profiles:
    active: dev

  datasource:
        ds1:
          username: root
          password: ENC(ey/INZfInTEGpFnu23IabA==)
          jdbc-url: jdbc:mysql://localhost:3306/springboot01?serverTimeZone=UTC&characterEncoding=utf8
          driver-class-name: com.mysql.jdbc.Driver
        ds2:
          username: root
          password: ENC(ey/INZfInTEGpFnu23IabA==)
          jdbc-url: jdbc:mysql://localhost:3306/springboot02?serverTimeZone=UTC&characterEncoding=utf8
          driver-class-name: com.mysql.jdbc.Driver

pagehelper:
  # 是否启用分页合理化。
  # 如果启用，当pagenum<1时，会自动查询第一页的数据，当pagenum>pages时，自动查询最后一页数据；
  # 不启用的，以上两种情况都会返回空数据
  reasonable: true
  # 默认值false，分页插件会从查询方法的参数值中，自动根据上面 params 配置的字段中取值，查找到合适的值时就会自动分页。
  support-methods-arguments: true
  params: count=countSql
  # 指定数据库，不指定的话会默认自动检测数据库类型
  auto-dialect: mysql
  # 用于从对象中根据属性名取值，
  # 可以配置 pageNum,pageSize,count,pageSizeZero,reasonable，不配置映射的用默认值，
  # 默认值为pageNum=pageNum;pageSize=pageSize;count=countSql;reasonable=reasonable;pageSizeZero=pageSizeZero
