server:
  port: 8081
  address: 127.0.0.1
  tomcat:
    uri-encoding: UTF-8

mybatis-plus:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.lyp.count
  configuration:
    # 打印sql
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #是否开启自动驼峰命名规则映射，即从经典数据库列名 A_COLUMN 到经典 Java 属性名 aColumn 的类似映射。
    map-underscore-to-camel-case: true

spring:
  profiles:
    active: dev
  datasource:
    dynamic:
        primary: master
        datasource:
          master:
            username: root
            password: ENC(ey/INZfInTEGpFnu23IabA==)
            url: jdbc:mysql://localhost:3306/springboot01?serverTimeZone=UTC&characterEncoding=utf8
            driver-class-name: com.mysql.jdbc.Driver
          slave:
            username: root
            password: ENC(ey/INZfInTEGpFnu23IabA==)
            url: jdbc:mysql://localhost:3306/springboot02?serverTimeZone=UTC&characterEncoding=utf8
            driver-class-name: com.mysql.jdbc.Driver
